### ISSUE TITLE
Moving from Ruby 2.5.1 to Ruby 2.5.3 creates a new problem

### ISSUE THREAD

**Issue by Rajagopalan-M** [kapoorlakshya/ffmpeg-screenrecorder#41]
@kapoorlakshya 

Hi, I have moved from Ruby 2.5.1 to Ruby 2.5.3, now it's throwing this error

FFMPEG::Error: [gdigrab @ 000002a00ad4a540] Invalid properties, aborting
 title=OleMainThreadWndName: I/O error

```
ffmpeg.log

ffmpeg version N-93075-gb429c86d84 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 46.100 / 58. 46.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[gdigrab @ 000001a07c30a540] Found window OleMainThreadWndName, capturing 0x0x32 at (0,0)
[gdigrab @ 000001a07c30a540] Invalid properties, aborting
title=OleMainThreadWndName: I/O error

```

**Comment by kapoorlakshya** [comment]
The problem is with`title=OleMainThreadWndName`. Make sure the title is exactly what's displayed in the UI. 

#37 will address this soon.

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya  I don't know how to resolve this problem, Can you please install Ruby 2.5.3 and check whether it's running.

**Comment by kapoorlakshya** [comment]
Can you share the same details that you shared earlier? Also the output from `#fetch` i.e. list of available titles.

It's not a Ruby problem, but the title name.

**Comment by kapoorlakshya** [comment]
As you can see here, all major Ruby 2.x versions are supported - https://travis-ci.org/kapoorlakshya/ffmpeg-screenrecorder

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya 

This line 

`puts FFMPEG::WindowTitles.fetch('firefox').last`

is printing 

`AllianzGo - Mozilla Firefox`

When I use 2.5.1 but error happens in this line when I use 2.5.3

ArgumentError: invalid byte sequence in UTF-8

  0) Scenerio9-Test1
     ?[31mFailure/Error:?[0m
     ?[31m  titles = `tasklist /v /fi "imagename eq #{application}.exe" /fo list | findstr  Window`?[0m
     ?[31m             .split("\n")?[0m
     ?[31m             .map { |i| i.gsub(IGNORED_WINDOW_TITLES, '') }?[0m
     ?[31m             .reject(&:empty?)?[0m
     ?[31m?[0m
     ?[31mArgumentError:?[0m

**Comment by kapoorlakshya** [comment]
HI @Rajagopalan-M , that is a different error than the first one your reported. This is a known issue and here are the workarounds - https://github.com/kapoorlakshya/ffmpeg-screenrecorder/wiki/Invalid-byte-sequence-in-UTF-8

Manually copy-pasting the title as `input: 'AllianzGo - Mozilla Firefox'` should work.

**Comment by kapoorlakshya** [comment]
Another thing you could do is to start the recorder before you navigate to the website. That way the title will simply be 'Mozilla Firefox'.

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya 

Hi, Now I have set the title this way

```
 opts = {input: "AllianzGo - Mozilla Firefox",
                    output: File.expand_path("Output/Video/#{scenario}/#{testCase.first + '_' + testCase[1]}.mp4"),
                    framerate: 15}
            @recorder = FFMPEG::ScreenRecorder.new(opts)
```

This is also working in 2.51 but not 2.5.3.

**Comment by kapoorlakshya** [comment]
What's the error in 2.5.3?

**Comment by Rajagopalan-M** [comment]
```
ArgumentError: invalid byte sequence in UTF-8

  0) StringRayTest1
     ?[31mFailure/Error:?[0m
     ?[31m  raw_list   = `tasklist /v /fi "imagename eq #{application}.exe" /fo list | findstr  Window`?[0m
     ?[31m                 .split("\n")?[0m
     ?[31m                 .select { |t| t.match?(/#{application}/i) } # Narrow down to given application?[0m
     ?[31m?[0m
     ?[31mArgumentError:?[0m
     ?[31m  invalid byte sequence in UTF-8?[0m
     ?[36m# ./Rspec_File.rb:107:in `block (5 levels) in <top (required)>'?[0m

```

**Comment by kapoorlakshya** [comment]
Are you using the exact same opts in both? `input: 'AllianzGo - Mozilla Firefox'`

**Comment by Rajagopalan-M** [comment]
@kapoorlakshya I am using this
```

  opts = {input: FFMPEG::WindowTitles.fetch('firefox').last,
                    output: File.expand_path("Output/Video/#{scenario}/#{testCase.first + '_' + testCase[1]}.mp4"),
                    framerate: 15}
```

This line `FFMPEG::WindowTitles.fetch('firefox').last` is returning this value `AllianzGo - Mozilla Firefox`.

**Comment by kapoorlakshya** [comment]
Use `input: 'AllianzGo - Mozilla Firefox'` instead of `input: FFMPEG::WindowTitles.fetch('firefox').last`.

`FFMPEG::WindowTitles.fetch('firefox')` is just a helper to get you the titles. For cases like this one, just copy-paste the window title for `input`.

I'll update the README to explain this.

**Comment by kapoorlakshya** [comment]
@Rajagopalan-M Did you figure it out?

**Comment by Rajagopalan-M** [comment]
Hi, Ruby 2.5.1 is working fine for me only with firefox, So I left it
there.

**Comment by kapoorlakshya** [comment]
Sounds good 👍
